# Generated by Django 5.2 on 2025-04-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(max_length=512, unique=True)),
                ('email', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('group_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoGitlabAct',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador')),
                ('student_email', models.CharField(blank=True, max_length=512, null=True)),
                ('gitlabact_total_commits', models.BigIntegerField()),
                ('gitlabact_avg_lines_added', models.BigIntegerField()),
                ('gitlabact_avg_lines_deleted', models.BigIntegerField()),
                ('gitlabact_avg_lines_per_commit', models.BigIntegerField()),
                ('gitlabact_active_days', models.BigIntegerField()),
                ('gitlabact_last_minute_commits', models.BigIntegerField()),
                ('gitlabact_total_merge_requests', models.BigIntegerField()),
                ('gitlabact_merged_requests', models.BigIntegerField()),
                ('gitlabact_review_comments_given', models.BigIntegerField()),
                ('gitlabact_review_comments_received', models.BigIntegerField()),
                ('gitlabact_total_issues_created', models.BigIntegerField()),
                ('gitlabact_total_issues_assigned', models.BigIntegerField()),
                ('gitlabact_issues_resolved', models.BigIntegerField()),
                ('gitlabact_issue_participation', models.BigIntegerField()),
                ('gitlabact_branches_created', models.BigIntegerField()),
                ('gitlabact_merges_to_main_branch', models.BigIntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
            ],
            options={
                'unique_together': {('student_email', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previsao_id', models.BigIntegerField()),
                ('prev_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('nota_prevista', models.BigIntegerField()),
                ('risco_reprovar', models.BooleanField()),
                ('data_previsao', models.DateField(unique=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
            options={
                'unique_together': {('previsao_id', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PrevisaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.previsao')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=512, null=True)),
                ('link_gitlab', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('utilizador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AlunoGitlabactPrevisao',
            fields=[
                ('aluno_gitlabact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.alunogitlabact')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.previsao')),
            ],
        ),
    ]
