# Generated by Django 5.2 on 2025-04-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoGitlabAct',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador')),
                ('student_num', models.BigIntegerField()),
                ('mention_handle', models.BooleanField()),
                ('interval', models.BooleanField(blank=True, null=True)),
                ('total_commits', models.BigIntegerField()),
                ('sum_lines_added', models.BigIntegerField()),
                ('sum_lines_deleted', models.BigIntegerField()),
                ('sum_lines_per_commit', models.BigIntegerField()),
                ('active_days', models.BigIntegerField()),
                ('last_minute_commits', models.BooleanField()),
                ('total_merge_requests', models.BigIntegerField()),
                ('merged_requests', models.BigIntegerField()),
                ('review_comments_given', models.BigIntegerField()),
                ('review_comments_received', models.BigIntegerField()),
                ('total_issues_created', models.BigIntegerField()),
                ('total_issues_assigned', models.BigIntegerField()),
                ('issues_resolved', models.BooleanField()),
                ('issue_participation', models.BooleanField()),
                ('branches_created', models.BigIntegerField()),
                ('merges_to_main_branch', models.BigIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
            ],
            options={
                'unique_together': {('student_num', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador')),
                ('link_gitlab', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('prevision_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_category', models.CharField(max_length=255)),
                ('prev_grade', models.BigIntegerField()),
                ('faling_risk', models.BooleanField()),
                ('prev_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
            options={
                'unique_together': {('prev_date', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PrevisaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.previsao')),
            ],
            options={
                'unique_together': {('previsao', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='GrupoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'unique_together': {('grupo', 'project')},
            },
        ),
        migrations.CreateModel(
            name='AlunoGitlabactPrevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.previsao')),
                ('aluno_gitlabact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alunogitlabact')),
            ],
            options={
                'unique_together': {('aluno_gitlabact', 'previsao')},
            },
        ),
        migrations.CreateModel(
            name='TeacherGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'grupo')},
            },
        ),
    ]
