# Generated by Django 5.2 on 2025-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='link_gitlab',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
