# Generated by Django 5.2 on 2025-05-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alunogitlabact',
            unique_together={('group', 'handle', 'data_registo')},
        ),
    ]
