# Generated by Django 5.2 on 2025-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='activation_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
