# Generated by Django 5.2 on 2025-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teacher_link_gitlab'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
