# Generated by Django 5.2 on 2025-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilizador_activation_token_utilizador_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='teacherid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
