# Generated by Django 5.2 on 2025-04-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alunogitlabact_data_registo'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='aluno_gitlabact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.alunogitlabact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previsao',
            name='prev_category',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='prev_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
