# Generated by Django 5.2 on 2025-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_utilizador_teacherid_alter_utilizador_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='teacherid',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
