# Generated by Django 5.2 on 2025-04-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_utilizador_teacherid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='password',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
