# Generated by Django 5.2 on 2025-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_utilizador_email_alter_utilizador_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
