# Generated by Django 5.2 on 2025-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_utilizador_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
